name: Azure Static Web Apps CI/CD
on:
  push:
    branches:
      - "**"
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    env:
      server_uri: "https://braustin-server-staging.herokuapp.com"
      goto_connect_client_id: $${{ secrets.GOTO_CONNECT_CLIENT_ID_STAGING }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Replace Env Vars
        id: envreplace
        run: build/env.sh
        shell: bash
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_ISLAND_04AEEC810 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
<<<<<<< HEAD:.github/workflows/azure-static-web-apps-thankful-island-04aeec810.yml
          server_url: 'https://braustin-server-staging.herokuapp.com/'

=======
          deployment_environment: "Staging"
>>>>>>> 67ae185f271c2dc2f4d5356ce156bfd6859c5342:.github/workflows/test-azure-static-web-apps-thankful-island-04aeec810.yml
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_ISLAND_04AEEC810 }}
          action: "close"
